Training:   0%|                                                                                                                        | 0/1729 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/packnet-sfm/scripts/train.py", line 81, in <module>
    train(args.file)
  File "/workspace/packnet-sfm/scripts/train.py", line 76, in train
    trainer.fit(model_wrapper)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 120, in fit
    self.train_with_eval(train_dataloader, module, optimizer)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 309, in train_with_eval
    output = module.training_step(batch, batch_idx)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 267, in training_step
    model_output = self.model(batch, progress=self.progress)  # removed unsupported masks kwarg
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/packnet-sfm/packnet_sfm/models/SemiSupCompletionModel.py", line 110, in forward
    self_sup_output = SelfSupModel.forward(
  File "/workspace/packnet-sfm/packnet_sfm/models/SelfSupModel.py", line 121, in forward
    self_sup_output = self.self_supervised_loss(
  File "/workspace/packnet-sfm/packnet_sfm/models/SelfSupModel.py", line 93, in self_supervised_loss
    return self._photometric_loss(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/packnet-sfm/packnet_sfm/losses/multiview_photometric_loss.py", line 375, in forward
    ref_warped = self.warp_ref_image(inv_depths, ref_image, intrinsics, ref_intrinsics, pose, image_size) # Pass image_size
  File "/workspace/packnet-sfm/packnet_sfm/losses/multiview_photometric_loss.py", line 166, in warp_ref_image
    'k': intrinsics['k'].clone().to(device),
TypeError: new(): invalid data type 'str'